@startuml
actor Vigilante
participant TicketController as TC
participant TicketService as TS
participant PuntoParqueoRepository as PR
participant TarifaCalculatorService as TCS
participant ApplicationEventPublisher as EVT
database BD

== Entrada ==
Vigilante -> TC : POST /api/tickets
TC -> TS : save(req)
TS -> PR : findByIdForUpdate(puntoId)  -- SELECT FOR UPDATE
PR -> BD : lock row
BD --> PR : punto libre
PR --> TS : Punto
TS -> BD : INSERT ticket (EN_CURSO)
TS -> EVT : TicketCreadoEvent
TS --> TC : TicketDTO
TC --> Vigilante : 201 Created

== Listener asíncrono ==
EVT -> "NotificationListener" : onTicketCreado
"NotificationListener" -> "SimpMessagingTemplate" : convertAndSend\n/topic/parqueadero/{id}\nTICKET_CREADO + SPOT_STATUS_CHANGE\n+ OCUPACION_ACTUALIZADA

== Salida ==
Vigilante -> TC : PATCH /api/tickets/{id}/salida
TC -> TS : cerrar(id)
TS -> BD : SELECT ticket
TS -> TCS : calcular(duracion, tarifa)
TCS --> TS : monto
TS -> BD : UPDATE ticket (CERRADO, fechaSalida, monto)
TS -> BD : INSERT factura (PENDIENTE, monto)
TS -> EVT : TicketCerradoEvent
TS --> TC : TicketDTO
TC --> Vigilante : 200 OK
@enduml